### ISSUE TITLE
Add trias to biotope flavor

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE-flavors#27]
Trias should be installed with:

```Dockerfile
RUN R -e devtools::install_github('trias-project/trias@5d0f27f76567c0d11021a3055c32ec521622ca36')
```

In PR #26, it was added in the jupyter image, but not in the cell images:

> trias is not included in the cell base at the moment. (It can neither be installed in the build image because it disrupts conda-pack, nor in the runtime image because the it doesn’t have the conda env.)

**Comment by gpelouze** [comment]
Checkout https://github.com/conda/conda/issues/6674

**Comment by gpelouze** [comment]
With [continuumio/miniconda3:4.12.0](https://hub.docker.com/layers/continuumio/miniconda3/4.12.0/images/sha256-58b1c7df8d69655ffec017ede784a075e3c2e9feff0fc50ef65300fc75aa45ae?context=explore):

```bash
$ conda install conda-build git
$ conda skeleton cran https://github.com/trias-project/trias --git-tag v2.0.7
$ conda build --R=4.3.0 r-trias
$ conda install /opt/conda/conda-bld/linux-64/r-trias-2.0.7-r43_0.tar.bz2
$ conda list | grep trias
r-trias                   2.0.7                     r43_0    <unknown>
```

Remaining issues:
- `conda skeleton cran <github url>` seems broken with conda >= [22.11.1](https://hub.docker.com/layers/continuumio/miniconda3/22.11.1-alpine/images/sha256-e49599e57c609834ffbc11de1df4b27c73e62b63548b1e4d91b587e3ff1d1a38?context=explore): 
```python
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
      File "/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 143, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "/opt/conda/lib/python3.10/site-packages/conda_build/plugin.py", line 59, in skeleton
        return execute(args)
      File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_skeleton.py", line 65, in execute
        api.skeletonize(
      File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 360, in skeletonize
        module.skeletonize(
      File "/opt/conda/lib/python3.10/site-packages/conda_build/skeletons/cran.py", line 996, in skeletonize
        source.git_source(
      File "/opt/conda/lib/python3.10/site-packages/conda_build/source.py", line 429, in git_source
        git_depth = int(source_dict.get("git_depth", -1))
    AttributeError: 'list' object has no attribute 'get'
```

- conda packages can only be built from git **tags**, but the initial container was using https://github.com/trias-project/trias/commit/5d0f27f76567c0d11021a3055c32ec521622ca36 which predates current tags.

**Comment by gpelouze** [comment]
We can add `flavors/biotope/naavre-cell-build.Dockerfile`:

```Dockerfile
FROM continuumio/miniconda3:4.12.0 as build-trias

RUN \
  conda install conda-build git && \
  conda skeleton cran https://github.com/trias-project/trias --git-tag v2.0.7 && \
  conda build --R=4.3 r-trias

FROM mambaorg/micromamba:1.5.6
RUN micromamba install -y -n base -c conda-forge conda-pack
ARG CONDA_ENV_FILE
COPY ${CONDA_ENV_FILE} environment.yaml
RUN micromamba create -y -n venv -f environment.yaml && \
    micromamba clean --all --yes

COPY --from=build-trias /opt/conda/conda-bld/linux-64/r-trias-2.0.7-r43_0.tar.bz2 .
RUN conda install r-trias-2.0.7-r43_0.tar.bz2
```

However, the last step needs to be translated from conda to micromamba, which does not support installing from `.tar.bz2` (https://github.com/mamba-org/mamba/issues/2291). Let's wait for micromamba v2 which will add support for it.
